FROM alpine:3.21.0

RUN apk add --no-cache \
    certbot \
    openssl

WORKDIR /certs

ENV DOMAIN=""
ENV EMAIL=""

COPY certbot-generate.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/certbot-generate.sh

ENTRYPOINT ["/usr/local/bin/certbot-generate.sh"] 